// =============================================================================
// storyline.js — The Cartographers of Chance
// Place this file in your js/ folder.
// Call showBeat(beatId, options) from game.js at the appropriate triggers.
// =============================================================================

// ---------------------------------------------------------------------------
// INTRO CINEMATIC — IMAGE SLIDESHOW (Part 1: Opening Cinematic)
// ---------------------------------------------------------------------------
//
// Each slide shows one image from images/Intro/Stoxels_Intro/ (1.jpeg ... 24.jpeg)
// for `duration` milliseconds, with `text` overlaid on top.
// After the duration elapses, it auto-advances to the next slide.
// Clicking / pressing space also advances early.
// After the last slide, the cinematic closes and onComplete fires.
//
// Adjust `duration` per-slide as needed, or change DEFAULT_SLIDE_DURATION_MS
// below for a global default.
// ---------------------------------------------------------------------------

const INTRO_CINEMATIC_SLIDES = [
    { image: "1.jpeg", text: "Reality is not made of matter.", duration: 8000 },
    { image: "2.jpeg", text: "It is made of data.", duration: 8000 },
    { image: "3.jpeg", text: "Probabilities. Statistical patterns. All of it woven into a living fabric - The Sample Space.", duration: 12000 },
    { image: "4.jpeg", text: "Everything that exists - mountains, oceans, creatures, time itself - is output. Generated by an ancient device.", duration: 12000 },
    { image: "5.jpeg", text: "Built long ago, by a civilisation of scholars who called themselves the First Cartographers.", duration: 11000 },
    { image: "6.jpeg", text: "Their greatest achievement - they called it the Apex of Stochastics.", duration: 9000 },
    { image: "7.jpeg", text: "Designed to keep the Sample Space coherent. Forever.", duration: 9000 },
    { image: "8.jpeg", text: "Ensuring randomness stayed honest - that the universe kept generating a coherent reality.", duration: 11000 },
    { image: "9.jpeg", text: "But then came the Variance Collapse.", duration: 8000 },
    { image: "10.jpeg", text: "The Apex began to corrupt.", duration: 8000 },
    { image: "11.jpeg", text: "The Sample Space began to fracture.", duration: 8000 },
    { image: "12.jpeg", text: "Split into thirteen distorted regions, each warped by its own statistical anomaly.", duration: 11000 },
    { image: "13.jpeg", text: "Most of the First Cartographers were lost in the chaos that followed.", duration: 10000 },
    { image: "14.jpeg", text: "A handful survived, and retreated to a small outpost at the edge of the world.", duration: 10000 },
    { image: "15.jpeg", text: "The survivors founded a Guild, to keep what they knew from being lost a second time.", duration: 11000 },
    { image: "16.jpeg", text: "In three hundred years, nobody has reached the Apex again.", duration: 10000 },
    { image: "17.jpeg", text: "The thirteen regions have remained in flux ever since.", duration: 9000 },
    { image: "18.jpeg", text: "Locked in place - by manifestations of pure void called Stoxels.", duration: 9000 },
    { image: "19.jpeg", text: "Collapsed knots of warped probability, binding the corruption to this place and keeping the land from healing.", duration: 10000 },
    { image: "24.jpeg", text: "They cannot be destroyed. Not by force, not by magic - nothing the First Cartographers tried ever worked.", duration: 11000 },
    { image: "20.jpeg", text: "A Stoxel cannot be broken. It can only be solved - the hidden pattern found, and filled, by someone who reads the mathematical language it was written in.", duration: 13000 },
    { image: "21.jpeg", text: "The Cartographers' Guild has been training young recruits for this task." },
    { image: "22.jpeg", text: "They call themselves the Cartographers of Chance." },
    { image: "23.jpeg", text: "And you... are one of them." },
];



// Folder where the intro images live (relative to your index.html)
const INTRO_CINEMATIC_IMAGE_PATH = "images/Intro/Stoxels_Intro/";

// Default time each slide stays on screen (ms). Override per-slide via
// the optional `duration` field on a slide object.
const DEFAULT_SLIDE_DURATION_MS = 10000;

// How long the text/image fade transition takes (ms)
const SLIDE_FADE_MS = 500;


// ---------------------------------------------------------------------------
// SONG BEATS — karaoke-style intro (Part 1.5: vocal intro song)
// ---------------------------------------------------------------------------
//
// A "song" beat decouples images from text completely:
//   - `images` is its own timeline: [{ image, time }], time = ms from song start.
//     A new image is shown as soon as playback crosses that time.
//   - `lines` is the lyric timeline: each line is { words: [{ word, time }] }.
//     `time` on a word = the ms (from song start) at which that word should be
//     FULLY revealed (i.e. finished being "sung"). Letters within the word are
//     revealed by interpolating between the previous word's time and this one.
//   - `audio` is the path to the vocal track. Playback of this file IS the
//     master clock — both images and lyrics sync to audioEl.currentTime.
//
// HOW TO FILL IN REAL TIMESTAMPS:
//   Listen to the track and note, for each word, the moment (in ms) it
//   finishes being sung. _wordsFromLine() below is a placeholder generator
//   that spaces words evenly across a line — replace its output with real
//   timestamps once you've timed the vocal track (or use a tap-to-timestamp
//   tool to record them as you listen).
// ---------------------------------------------------------------------------

// _wordsFromLine — PLACEHOLDER timestamp generator.
// Splits a line into words and spaces their "fully revealed" times evenly
// between lineStartMs and lineEndMs. Replace with real per-word timestamps
// once you have them timed against the actual vocal track.
function _wordsFromLine(text, lineStartMs, lineEndMs) {
    const words = text.split(' ').filter(Boolean);
    const span = lineEndMs - lineStartMs;
    return words.map((word, i) => ({
        word,
        time: Math.round(lineStartMs + span * ((i + 1) / words.length)),
    }));
}

// Maximum number of lines that appear in any single contiguous song section
// (e.g. the longest verse/chorus). Used to reserve a fixed-height text block
// so the box doesn't resize/jump as lines accumulate within a section.
const MAX_SONG_SECTION_LINES = 8;

// INTRO_SONG — full intro song, timed from Stoxels_Intro_Song.srt.
// Each line's start/end comes directly from the SRT (real vocal timing).
// Word-level reveal within each line is still interpolated evenly across
// that line's SRT window via _wordsFromLine — true word-by-word timestamps
// would need finer-grained data than SRT provides (SRT is line-level only),
// but this means every line change is locked exactly to the vocals, and the
// typewriter effect within a line plays out at a steady pace across the
// real duration that line is actually sung for.
//
// Regenerate this block any time the SRT changes by re-running the same
// parse script used to build it (parses the .srt, emits one
// _wordsFromLine(...) call per cue with that cue's real start/end ms).
const INTRO_SONG = {
    audio: "audio/Intro/Stoxels_Intro_Song.mp3",
    imagePath: INTRO_CINEMATIC_IMAGE_PATH,

    // Image timeline — one change roughly every 2 lyric lines, snapped to
    // that line's real start time, cycling through images 1-24. Adjust
    // freely — this list is independent of the lyric timing below.
    images: [
        { image: "1.jpeg", time: 0 },
        { image: "2.jpeg", time: 23225 },
        { image: "3.jpeg", time: 29317 },
        { image: "4.jpeg", time: 35482 },
        { image: "5.jpeg", time: 54863 },
        { image: "6.jpeg", time: 61448 },
        { image: "7.jpeg", time: 67852 },
        { image: "8.jpeg", time: 74477 },
        { image: "9.jpeg", time: 80806 },
        { image: "10.jpeg", time: 87091 },
        { image: "11.jpeg", time: 93678 },
        { image: "12.jpeg", time: 100373 },
        { image: "13.jpeg", time: 106902 },
        { image: "14.jpeg", time: 113130 },
        { image: "15.jpeg", time: 132748 },
        { image: "16.jpeg", time: 139145 },
        { image: "17.jpeg", time: 145572 },
        { image: "18.jpeg", time: 151939 },
        { image: "19.jpeg", time: 159013 },
        { image: "20.jpeg", time: 164900 },
        { image: "21.jpeg", time: 171433 },
        { image: "22.jpeg", time: 177920 },
        { image: "23.jpeg", time: 184544 },
        { image: "24.jpeg", time: 190988 },
        { image: "1.jpeg", time: 199300 },
        { image: "2.jpeg", time: 209559 },
        { image: "3.jpeg", time: 221752 },
        { image: "4.jpeg", time: 228393 },
        { image: "5.jpeg", time: 235910 },
        { image: "6.jpeg", time: 249313 },
        { image: "7.jpeg", time: 255938 },
        { image: "8.jpeg", time: 262343 },
        { image: "9.jpeg", time: 272488 },
    ],

    // Lyric timeline — all 66 lines from the SRT, in order, using each
    // line's real start/end time as the word-reveal window. Each line also
    // carries a `section` label (Verse 1, Chorus, Bridge, etc.) — lines in
    // the same section accumulate in the display block; a new section
    // clears the block and starts fresh. See SONG_SECTION_ORDER below if
    // you need the max lines-per-section for layout sizing.
    lines: [
        { section: 'Verse 1', words: _wordsFromLine('They say the world is matter', 16692, 18667) },
        { section: 'Verse 1', words: _wordsFromLine('Stone and sea and skin', 19675, 22581) },
        { section: 'Verse 1', words: _wordsFromLine('But underneath the surface', 23225, 25651) },
        { section: 'Verse 1', words: _wordsFromLine('It\'s numbers running thin', 26501, 28594) },
        { section: 'Verse 1', words: _wordsFromLine('Just probabilities dancing', 29317, 31856) },
        { section: 'Verse 1', words: _wordsFromLine('In a fabric none can see', 32662, 34957) },
        { section: 'Verse 1', words: _wordsFromLine('This is the Sample Space we\'re born from', 35482, 38472) },
        { section: 'Verse 1', words: _wordsFromLine('This is how we came to be', 39004, 42025) },
        { section: 'Verse 2', words: _wordsFromLine('Every mountain, every ocean', 54863, 58005) },
        { section: 'Verse 2', words: _wordsFromLine('Every creature, every hour', 58447, 61123) },
        { section: 'Verse 2', words: _wordsFromLine('Was written by an ancient engine', 61448, 64188) },
        { section: 'Verse 2', words: _wordsFromLine('Built with old and patient power', 64630, 67490) },
        { section: 'Verse 2', words: _wordsFromLine('Scholars called the First Cartographers', 67852, 70922) },
        { section: 'Verse 2', words: _wordsFromLine('Raised it from the stone', 71604, 74152) },
        { section: 'Verse 2', words: _wordsFromLine('The Apex of all Stochastics', 74477, 77256) },
        { section: 'Verse 2', words: _wordsFromLine('Standing there alone', 77618, 80485) },
        { section: 'Pre-Chorus', words: _wordsFromLine('Built to keep the chaos honest', 80806, 83676) },
        { section: 'Pre-Chorus', words: _wordsFromLine('Built to hold the pattern true', 84173, 86804) },
        { section: 'Pre-Chorus', words: _wordsFromLine('Forever, they believed it', 87091, 89575) },
        { section: 'Pre-Chorus', words: _wordsFromLine('Forever, they thought they knew', 90018, 93219) },
        { section: 'Chorus', words: _wordsFromLine('But nothing built can last forever', 93678, 96858) },
        { section: 'Chorus', words: _wordsFromLine('Nothing measured stays the same', 97386, 99967) },
        { section: 'Chorus', words: _wordsFromLine('Something broke the Variance open', 100373, 103331) },
        { section: 'Chorus', words: _wordsFromLine('Something tore the world\'s frame', 103620, 106328) },
        { section: 'Chorus', words: _wordsFromLine('Thirteen pieces, scattered, warping', 106902, 109709) },
        { section: 'Chorus', words: _wordsFromLine('Thirteen wounds that never close', 110162, 112803) },
        { section: 'Chorus', words: _wordsFromLine('This is the Collapse we\'re living after', 113130, 116266) },
        { section: 'Chorus', words: _wordsFromLine('This is the world the Cartographers chose', 116508, 122459) },
        { section: 'Verse 3', words: _wordsFromLine('Most of them were lost that day', 132748, 135677) },
        { section: 'Verse 3', words: _wordsFromLine('Swallowed by the breaking tide', 135969, 138687) },
        { section: 'Verse 3', words: _wordsFromLine('A handful crawled to the edges of the world', 139145, 142681) },
        { section: 'Verse 3', words: _wordsFromLine('And built a Guild to hide', 142927, 145154) },
        { section: 'Verse 3', words: _wordsFromLine('Three hundred years have passed us', 145572, 148434) },
        { section: 'Verse 3', words: _wordsFromLine('And no one\'s touched the Apex since', 148915, 151645) },
        { section: 'Verse 3', words: _wordsFromLine('Thirteen regions caught in flux', 151939, 154741) },
        { section: 'Verse 3', words: _wordsFromLine('Held by something we call Stoxels', 155065, 158408) },
        { section: 'Pre-Chorus', words: _wordsFromLine('Pure void, locked in pattern', 159013, 161618) },
        { section: 'Pre-Chorus', words: _wordsFromLine('Nothing breaks them, nothing can', 161994, 164497) },
        { section: 'Pre-Chorus', words: _wordsFromLine('No blade, no spell, no fire', 164900, 167240) },
        { section: 'Pre-Chorus', words: _wordsFromLine('Only the mind of one who understands', 167616, 171106) },
        { section: 'Chorus', words: _wordsFromLine('But nothing built can last forever', 171433, 174721) },
        { section: 'Chorus', words: _wordsFromLine('Nothing measured stays the same', 175003, 177587) },
        { section: 'Chorus', words: _wordsFromLine('A Stoxel can\'t be broken open', 177920, 180755) },
        { section: 'Chorus', words: _wordsFromLine('Only solved, only named', 181123, 184210) },
        { section: 'Chorus', words: _wordsFromLine('Read the language hidden in it', 184544, 187415) },
        { section: 'Chorus', words: _wordsFromLine('Find the number, find the door', 187746, 190625) },
        { section: 'Chorus', words: _wordsFromLine('This is the Collapse we\'re living after', 190988, 193887) },
        { section: 'Chorus', words: _wordsFromLine('This is what we\'re fighting for', 194169, 197974) },
        { section: 'Bridge', words: _wordsFromLine('The Guild has trained its children', 199300, 201354) },
        { section: 'Bridge', words: _wordsFromLine('For longer than they\'ve known', 201927, 208659) },
        { section: 'Bridge', words: _wordsFromLine('Calling themselves the Cartographers of Chance', 209559, 214629) },
        { section: 'Bridge', words: _wordsFromLine('Walking out alone', 215159, 221427) },
        { section: 'Bridge', words: _wordsFromLine('And maybe it was always you', 221752, 224173) },
        { section: 'Bridge', words: _wordsFromLine('Maybe it was always meant to be', 224586, 227939) },
        { section: 'Bridge', words: _wordsFromLine('The one who reads the pattern', 228393, 232468) },
        { section: 'Bridge', words: _wordsFromLine('The one who sets it free', 232754, 235707) },
        { section: 'Final Chorus', words: _wordsFromLine('Because nothing built can last forever', 235910, 239572) },
        { section: 'Final Chorus', words: _wordsFromLine('But nothing broken has to stay', 242852, 249108) },
        { section: 'Final Chorus', words: _wordsFromLine('Every Stoxel holds a number', 249313, 252381) },
        { section: 'Final Chorus', words: _wordsFromLine('Waiting for the one who\'ll stay', 252825, 255611) },
        { section: 'Final Chorus', words: _wordsFromLine('Thirteen regions, calling, calling', 255938, 258640) },
        { section: 'Final Chorus', words: _wordsFromLine('You\'re the answer they\'ve been waiting for', 259004, 262011) },
        { section: 'Final Chorus', words: _wordsFromLine('This is the Collapse we\'re living after', 262343, 265840) },
        { section: 'Final Chorus', words: _wordsFromLine('And you... you\'re walking through that door', 266042, 272165) },
        { section: 'Outro', words: _wordsFromLine('And you...', 272488, 274697) },
        { section: 'Outro', words: _wordsFromLine('Are one of them', 277866, 284259) },
    ],
};


// ---------------------------------------------------------------------------
// CHARACTER INTRO CINEMATICS — IMAGE SLIDESHOWS (Part 2: Character Intros)
// ---------------------------------------------------------------------------
//
// Same approach as INTRO_CINEMATIC_SLIDES above, but one slideshow per
// selectable character. Images live in their own per-character folders.
// ---------------------------------------------------------------------------

const STOX_INTRO_SLIDES = [
    { image: "1.jpeg", text: "Stox has spent his whole life in this archive.", duration: 9000 },
    { image: "2.jpeg", text: "He didn't write any of it. But he's read every word - every note, every survey log, every parameter the First Cartographers ever committed to paper.", duration: 12000 },
    { image: "3.jpeg", text: "He has been through it all. Repeatedly. Studying a catastrophe that happened three hundred years before he was born.", duration: 11000 },
    { image: "4.jpeg", text: "The timeline has never added up. The regions failed in the wrong order. The corruption spread in a pattern too deliberate to be random.", duration: 12000 },
    { image: "5.jpeg", text: "He has mapped every connection he could find. Cross-referenced every maintenance log against every structural failure.", duration: 11000 },
    { image: "6.jpeg", text: "The records point inward. Whatever corrupted the Apex came from someone who understood it completely.", duration: 10000 },
    { image: "7.jpeg", text: "One of the First Cartographers did this. He cannot find who. Or why.", duration: 9000 },
    { image: "8.jpeg", text: "The archive has no more answers to give him. He has read everything it contains.", duration: 10000 },
    { image: "9.jpeg", text: "Whatever is still hidden - it is out there. In the regions. In the Stoxels. In what was left behind when everything broke.", duration: 11000 },
    { image: "10.jpeg", text: "The records ran out of answers a long time ago. He has decided he is finished waiting.", duration: 10000 },
    { image: "11.jpeg", text: "The answer exists. He is going to find it...", duration: 8000 },
    { image: "12.jpeg", text: "...because he is unable to leave it unfound.", duration: 8000 },
];




const TRIX_INTRO_SLIDES = [
    { image: "1.jpeg", text: "Three hundred years ago, when the Apex broke, a faction of First Cartographers refused to call it an accident. The Guild called that heresy - and made an example of them.", duration: 11000 },
    { image: "2.jpeg", text: "They were stripped of name and record, and walked until the ground stopped pretending to be stable. They built a life in the one place nobody else wanted: the Regression Rift.", duration: 11000 },
    { image: "3.jpeg", text: "Generations passed inside it. The correlations turned hostile. The colony got smaller every year the world did not get kinder.", duration: 10000 },
    { image: "4.jpeg", text: "Trix was born in the only room still lit - the OLS Observatory - surrounded by a colony that was mostly graves by then. The Rift was the only teacher she ever had, and it taught her that if something happens near you often enough, it starts to listen back.", duration: 13000 },
    { image: "5.jpeg", text: "Then the Observatory's numbers changed. The variance she had trusted her whole life began sliding toward a value with no room left in it for chance.", duration: 11000 },
    { image: "6.jpeg", text: "Whatever was rewriting that number was not going to stop at the Rift's edge. Her family had been exiled three hundred years ago for calling the Collapse deliberate. She finally had proof.", duration: 12000 },
    { image: "7.jpeg", text: "She left the only way anyone ever has - at night, with a lantern, and no plan to come back until it mattered.", duration: 9000 },
    { image: "8.jpeg", text: "The walls of the Outpost still remembered her family's name. Nobody inside them did.", duration: 8000 },
    { image: "9.jpeg", text: "But the Guild's archive did. Three hundred years of records her family had never been allowed to read - and somewhere in them, the answer her instruments were screaming about.", duration: 11000 },
    { image: "10.jpeg", text: "The Guild has rules about who gets access to the archive. Qualifications. Methodology. Approved techniques.", duration: 9000 },
    { image: "11.jpeg", text: "They explained it slowly, like she might not follow. Unsanctioned access was forbidden. She lacked the proper credentials. They had not noticed her hands the entire time they were talking.", duration: 12000 },
    { image: "12.jpeg", text: "She thanked them for their time and left through the exit. The records that mattered had already changed pockets.", duration: 9000 },
    { image: "13.jpeg", text: "The Guild can keep its rulebook. She has what she came for, and a place to start. The world can try to stop her - that would at least make it interesting.", duration: 11000 },
];


const SYLA_INTRO_SLIDES = [
    { image: "1.jpeg", text: "Syla has never needed instruments to read the wild places. She knows which roots talk to which trees, why the mushrooms only glow on certain nights, and what the squirrels are nervous about before she is.", duration: 15000 },
    { image: "2.jpeg", text: "She has walked this thicket a thousand times. It has worn the same quiet scar for three hundred years, locked tight by something old that the animals stopped fearing generations ago. Today, for the first time she has ever seen, it woke up.", duration: 15000 },
    { image: "3.jpeg", text: "The Cartographers would call this background corruption - old news, sealed since the Variance Collapse. Except it has never spread before. Not in three hundred years of records, and not in nineteen years of her own. She starts writing down everything, the way she always does when something feels wrong.", duration: 15000 },
    { image: "4.jpeg", text: "From the ridge above her valley, the scale of it finally shows itself. What she thought was one bruised hollow is dozens, all connected, all spreading in the same direction at once. This was never going to stay her secret to fix alone.", duration: 15000 },
    { image: "5.jpeg", text: "Deep inside the spreading wound, she finds something that should not exist there: a single leaf, glowing steady gold in a place where nothing should glow at all. She does not know what it is yet. She knows it matters.", duration: 15000 },
    { image: "6.jpeg", text: "Back home, she pulls every notebook she owns onto the floor of her tent - nineteen years of careful, unglamorous observation, kept because the patterns were beautiful, never because anyone asked her to keep them. Somewhere in here is an answer.", duration: 15000 },
    { image: "7.jpeg", text: "She finds it on a page she sketched as a child: a tangled, thorny shape she once copied from a vine outside her tent, just because she liked how it curled. The same shape is now carved into the corruption spreading through her valley. It was never just a vine.", duration: 15000 },
    { image: "8.jpeg", text: "She lays her own years side by side for the first time. Year twelve: mild, barely worth a footnote. Year twenty: severe, spreading, aggressive. Read end to end, it does not look like decay. It looks like a curve.", duration: 15000 },
    { image: "9.jpeg", text: "She draws it out properly, axis and all, and her stomach drops at what the line does near the end. This was never random drift. Something has been pushing, and it has started pushing harder.", duration: 15000 },
    { image: "10.jpeg", text: "Her notebooks can tell her what is happening. They cannot tell her why, or whether anyone has seen a curve like this before. There is only one place old enough to know: the Cartographers' Outpost, and whatever they have kept locked in that archive for three centuries.", duration: 15000 },
    { image: "11.jpeg", text: "The old cartographer at the window looks at her mud-stained boots and her hand-bound notebooks and does not bother hiding his doubt. Field notes are not data, he tells her. She decides she will just have to show him the difference.", duration: 15000 },
    { image: "12.jpeg", text: "Nobody assigns her a desk, so she makes her own - her own pathways and river-logs spread open beside the Guild's official records, comparing line for line until the two start agreeing with each other.", duration: 15000 },
    { image: "13.jpeg", text: "She lays it all out in the research division's courtyard: her data, their archive, and the pattern that connects every wound on the map to a point that can be reached and treated, if someone is willing to walk there with the right kind of patience. She calls them purification nodes. Half the room calls it nonsense.", duration: 15000 },
    { image: "14.jpeg", text: "Nobody offers to come with her. That is fine. She has spent her whole life being the only one listening closely enough to notice things. She steps through the gate at dusk, one small light cupped in her hand, headed for the nearest wound on her map.", duration: 15000 },
];

// Folders where the per-character intro images live (relative to your index.html)
const STOX_INTRO_IMAGE_PATH = "images/Intro/Stox_Intro/";
const TRIX_INTRO_IMAGE_PATH = "images/Intro/Trix_Intro/";
const SYLA_INTRO_IMAGE_PATH = "images/Intro/Syla_Intro/";


// ---------------------------------------------------------------------------
// STORY BEATS
// ---------------------------------------------------------------------------

const STORY_BEATS = {

    // -------------------------------------------------------------------------
    // OPENING FLOW — image slideshow cinematic
    // -------------------------------------------------------------------------

    intro_cinematic: {
        song: INTRO_SONG
    },

    // -------------------------------------------------------------------------
    // CHARACTER INTROS — pass { character: 'stox' | 'trix' | 'syla' }
    // Each is its own image slideshow (same approach as intro_cinematic).
    // -------------------------------------------------------------------------

    character_intro: {
        characterVariants: {
            stox: {
                slides: STOX_INTRO_SLIDES,
                imagePath: STOX_INTRO_IMAGE_PATH
            },
            trix: {
                slides: TRIX_INTRO_SLIDES,
                imagePath: TRIX_INTRO_IMAGE_PATH
            },
            syla: {
                slides: SYLA_INTRO_SLIDES,
                imagePath: SYLA_INTRO_IMAGE_PATH
            }
        }
    },






    // -------------------------------------------------------------------------
    // FIRST CONVERGENCE STOXEL
    // -------------------------------------------------------------------------

    first_convergence: {
        pages: [
            [
                "You felt it when the Stoxel resolved — not just the puzzle clicking into place, but something larger. A shockwave of mathematical energy, propagating outward through the Substrate.",
                "Back at the Outpost, a new branch of the Atlas illuminated.",
                "The First Cartographers left it there. They always knew someone would eventually understand enough to see it.",
            ],
            [
                "But something else is nagging at you.",
                "The Stoxel's formation pattern was not consistent with the Variance Collapse's known behaviour. It was too structured. Too targeted.",
                "You file it away for now.",
                "You are going to find more of them.",
            ]
        ]
    },

    // -------------------------------------------------------------------------
    // REGION ENTRY BEATS — triggered on first visit only
    // -------------------------------------------------------------------------

    region_1: {
        pages: [
            [
                "Probability Peaks.",
                "The mountains here shift based on probability distributions. Paths that existed yesterday may not exist today. Landmarks change when you are not looking.",
                "The First Cartographers loved this place. It was where they first proved that apparent randomness contains structure. Their survey notes here are the most optimistic in the archive.",
            ]
        ]
    },

    region_2: {
        pages: [
            [
                "Bayesian Bay.",
                "The tidal patterns here run on Bayesian updating — the sea changes based on what it has observed, not what physics should dictate. The creatures here are the most intelligent in the known world. In an environment that rewards updating your beliefs, intelligence is a survival trait.",
                "The Collapse did not make this place more chaotic. It made it too certain. The Bay locked onto a prior and stopped updating. The sea no longer responds to new information.",
                "It is frozen in a belief that is three hundred years out of date.",
            ]
        ]
    },

    region_3: {
        pages: [
            [
                "Sampling Savanna.",
                "This was the First Cartographers' primary field research site — a living dataset where animal migrations, plant growth, and weather all followed statistical laws so cleanly that early Cartographers could sit here and watch probability work in real time.",
                "The Collapse introduced sampling bias. The data is still flowing, but it is wrong in ways that are not immediately obvious.",
                "Something is contaminating the sample — and the contamination is spreading.",
            ]
        ]
    },

    region_4: {
        pages: [
            [
                "The Distribution Den.",
                "The cave shapes here are bell curves. The stalactite patterns follow power laws. The underground rivers run in Poisson processes. This is where the Substrate is closest to the surface — where the mathematical foundations of reality are literally visible in the rock.",
                "The Collapse hit the Den at a structural level. The distributions themselves are malformed. Bell curves with missing tails. Power laws that reverse.",
                "The cave system is physically unstable because the geology is built on the mathematics — and the mathematics is broken.",
            ]
        ]
    },

    region_5: {
        pages: [
            [
                "Regression Rift.",
                "Here, if two things happen at the same time often enough, they begin to cause each other. The landscape folds back on itself. Rivers run toward their own sources. The flora grows in patterns that reinforce themselves until they collapse.",
            ],
            [
                "This region was someone's home, once.",
            ]
        ]
    },

    region_6: {
        pages: [
            [
                "The Vortex of Possibilities.",
                "The Vortex is not a region the First Cartographers built. It is the Variance Collapse, made visible — the place where the corruption entered the Substrate, spinning ever since, pulling probability fields from surrounding regions into its spiral and churning them into noise.",
                "Most Cartographers assume this is where it started.",
                "They are wrong.",
            ]
        ]
    },

    region_7: {
        pages: [
            [
                "Expectation Plateau.",
                "The First Cartographers made their greatest theoretical breakthrough here — the formalisation of expected value. The proof is carved into the plateau's bedrock in letters thirty metres high.",
                "Someone has been defacing it. Not randomly. Systematically. Certain symbols altered to make the proof incorrect. The plateau's stability depends on the proof being intact, and it is failing.",
            ],
            [
                "This was not the Collapse.",
                "This was deliberate.",
            ]
        ]
    },

    region_8: {
        pages: [
            [
                "Data Delta.",
                "Everything that happens anywhere in the world eventually leaves a data trace. Those traces flow through the Delta. The First Cartographers built processing stations here to read the world's information in near-real time.",
                "The Collapse corrupted the data streams. The Delta now carries noise mixed with signal in proportions that make meaningful extraction almost impossible.",
                "Almost.",
            ]
        ]
    },

    region_9: {
        pages: [
            [
                "Stochapolis.",
                "A civilisation once believed that sufficiently precise machines could eliminate probability entirely — reduce all outcomes to certainty through sufficiently advanced computation. They called this Total Determination and spent centuries building Stochapolis to achieve it.",
                "The Variance Collapse destroyed their project and destroyed them. Their machines are still running. Gears turning, calculators clattering through infinite loops — all of it generating precisely nothing.",
            ],
            [
                "But the machines are not entirely empty.",
                "Something has moved in.",
            ]
        ]
    },

    region_10: {
        pages: [
            [
                "Hypothesis Hinterlands.",
                "The conceptual layer of the Substrate — where mathematical ideas exist as abstract structures — has collapsed into the physical layer here. Theories have taken physical form.",
                "True hypotheses are stable, almost tame. False hypotheses have become predators: aggressive, territorial, and dangerous precisely because they are wrong and do not know it.",
                "The number of possible wrong answers is vastly larger than the number of right ones.",
            ]
        ]
    },

    region_11: {
        pages: [
            [
                "Frequency Forest.",
                "The trees grow in Fibonacci spirals. The animals move in Markov chains. The weather repeats on exactly the same cycle, day after day. The First Cartographers noted it as beautiful.",
                "The Collapse made it compulsive. The patterns cannot stop repeating even when the underlying data has changed.",
                "At the forest's centre, something is forcing the repetition — because repetition feels like certainty to something that fears randomness.",
            ]
        ]
    },

    region_12: {
        pages: [
            [
                "Null Hypothesis Void.",
                "Entire statistical concepts have been erased from existence here. Things that should exist simply do not. The region is not dark because light is absent — it is dark because the concept of light's presence has been removed from local probability space.",
                "This is also where its influence is strongest.",
                "And here, for the first time, it does not send a creature.",
                "It sends a voice.",
            ],
            [
                "\"You have been solving the Collapse as though it were an accident. It was not. Every Stoxel you have cleared, every region you have stabilised — you have been undoing three hundred years of careful work.\"",
                "\"I would like you to understand why that work was done before you decide to finish undoing it.\"",
                "\"In a universe governed by probability, suffering is not possible. It is guaranteed. For any sufficiently long timeline, every bad outcome has probability 1. Every loss. Every death. Every failure.\"",
                "\"I am not the villain of this story. I am the only one who finished reading it.\"",
            ]
        ]
    },

    region_13: {
        pages: [
            [
                "Parameter Plains.",
                "The fundamental parameters of this world's mathematics — θ, μ, σ — are physically inscribed across these plains. They are not decorative. They are load-bearing. The values here are the values the Substrate uses to generate reality's probability fields everywhere.",
                "Someone is rewriting them. Carefully. Deliberately. One parameter at a time, shifting the world's fundamental constants toward values that produce lower and lower variance.",
                "The trajectory, if completed, leads to a single point: zero variance everywhere. A world where every probability distribution has collapsed to a single certain outcome.",
            ],
            [
                "His name was Verun.",
                "He was a First Cartographer. After decades of mapping the Substrate, he proved mathematically that in a universe governed by probability, suffering is guaranteed — and he concluded that probability itself was the source of all suffering. That the only humane act was to collapse all variance to zero.",
                "He called this The Final Null. He introduced corrupted parameters into the Apex to achieve it.",
                "He did not survive to see his plan succeed.",
                "But the parameters have been working for three hundred years.",
                "And they are nearly finished.",
            ]
        ]
    },

    // -------------------------------------------------------------------------
    // CLASS EVENTS
    // -------------------------------------------------------------------------

    class_unlock: {
        // Pass { className: 'Mathmagician' | 'Statistician' | 'Probabilist' }
        // The class-specific line is appended after the shared opening.
        shared: [
            "The Trial Chamber was not designed to teach you.",
            "It was designed to find out whether you already knew.",
            "You did.",
        ],
        classLines: {
            Mathmagician: "Numbers bend for you differently now. They always did.",
            Statistician: "You do not guess. You estimate — with confidence intervals the Guild did not think were possible.",
            Probabilist: "You have stopped asking what will happen. You ask what is likely. The difference turns out to matter enormously.",
        },
        // Fallback if class name isn't listed above
        defaultClassLine: "The Guild has a name for what you are now. You are starting to suspect the name is too small.",
    },

    class_mastered: {
        pages: [
            [
                "The Guild's texts end here.",
                "Every technique they documented, every method they preserved from the First Cartographers — you have learned it and pushed past it.",
                "What comes next is not in any archive.",
            ]
        ]
    },

    // -------------------------------------------------------------------------
    // ASCENDENCY CLASSES
    // -------------------------------------------------------------------------



    ascendency_unlock: {
        // Pass { ascendencyClass: 'Outlier' | 'Actuary' | etc. }
        variants: {
            Outlier: [
                [
                    "You do not fit the distribution. You never did. The Ascendency Trial simply made it undeniable.",
                    "An Outlier does not reject the rules of probability. They exist outside the range where those rules make confident predictions.",
                    "That is not a flaw.",
                    "In a world trying to eliminate variance, it is the most dangerous thing you can be.",
                ]
            ],
            Actuary: [
                [
                    "You have learned to price risk across timelines most Cartographers cannot see.",
                    "The Ascendency Trial asked you to calculate the cost of outcomes that have not happened yet.",
                    "You answered correctly.",
                    "The Apex's entities are going to find that deeply inconvenient.",
                ]
            ],
            Recursionist: [
                [
                    "The solution contains itself. You understood this before the Trial finished explaining it.",
                    "A Recursionist does not solve problems linearly. They find the point where the problem solves itself — and stand there.",
                ]
            ],
            Markovian: [
                [
                    "The past is irrelevant. The present state is everything.",
                    "A Markovian moves through probability space without carrying the weight of history. Each moment is its own complete calculation.",
                    "The Null has been planning for three hundred years.",
                    "You have been planning for exactly as long as you need.",
                ]
            ],
            Bayesian: [
                [
                    "You do not have a prior. You have a current best estimate, subject to revision upon new evidence.",
                    "A Bayesian is the most dangerous thing in an uncertain world: someone who updates correctly, every time, without ego.",
                    "The Null stopped updating three hundred years ago.",
                ]
            ],
            RandomWalker: [
                [
                    "There is no path. There is only the next step, and the one after.",
                    "A Random Walker has learned that in a Substrate governed by probability, the most honest way to navigate is to trust the process and accumulate position over time.",
                    "It looks like wandering.",
                    "It is not wandering.",
                ]
            ],
        },
        defaultVariant: [
            [
                "The Ascendency Trial did not promote you. It mutated you.",
                "You went in as one thing and came out as something the Guild's textbooks do not have a chapter for.",
                "Start writing one.",
            ]
        ]
    },

    // -------------------------------------------------------------------------
    // ENDGAME
    // -------------------------------------------------------------------------

    nexus_opens: {
        pages: [
            [
                "For three hundred years, this door has been closed.",
                "It does not open because you forced it. It opens because the world is finally stable enough to let you through.",
                "Thirteen regions. Hundreds of Stoxels. The work of the First Cartographers, continued.",
            ],
            [
                "The Apex is above you.",
                "Whatever Verun set in motion up there is nearly complete.",
                "You have earned the right to answer it.",
            ]
        ]
    },

    final_choice: {
        pages: [
            [
                "The Null is not a monster.",
                "It is a conclusion drawn from real mathematics by someone who could not bear what the mathematics meant.",
                "Verun was not wrong about the proof. Suffering, in a probabilistic universe, is guaranteed given enough time.",
                "He was right.",
                "He was wrong about what to do with that truth.",
            ],
            [
                "You are about to tell it what you think the answer is.",
            ]
        ]
    },


};


// ---------------------------------------------------------------------------
// RENDERER
// ---------------------------------------------------------------------------

const StorylineRenderer = (() => {

    // -- Styling constants --
    const STYLES = {
        overlay: `
            position: fixed;
            top: 0; left: 0;
            width: 100%; height: 100%;
            background: #000;
            z-index: 9999;
            display: flex;
            flex-direction: column;
            align-items: center;
            justify-content: center;
            cursor: pointer;
            overflow: hidden;
        `,
        textBox: `
            max-width: 680px;
            width: 90%;
            text-align: center;
        `,
        line: `
            font-family: 'Georgia', 'Times New Roman', serif;
            font-size: clamp(14px, 2.2vw, 18px);
            line-height: 1.85;
            color: rgba(255, 255, 255, 0);
            margin: 0 0 1.1em 0;
            transition: color 2s ease;
        `,
        // Lines that open with a quote mark are styled differently
        quotedLine: `
            font-family: 'Georgia', 'Times New Roman', serif;
            font-size: clamp(13px, 2vw, 16px);
            line-height: 1.9;
            color: rgba(255, 255, 255, 0);
            margin: 0 0 1em 0;
            font-style: italic;
            transition: color 2s ease;
        `,
        hint: `
            position: absolute;
            bottom: 36px;
            left: 50%;
            transform: translateX(-50%);
            font-family: 'Georgia', 'Times New Roman', serif;
            font-size: 20px;
            letter-spacing: 0.18em;
            color: rgba(255, 255, 255, 0);
            text-transform: uppercase;
            transition: color 2s ease;
            white-space: nowrap;
            pointer-events: none;
        `,
        skipBtn: `
            position: absolute;
            bottom: 28px;
            right: 36px;
            font-family: 'Georgia', 'Times New Roman', serif;
            font-size: 30px;
            letter-spacing: 0.18em;
            color: rgba(255, 255, 255, 0.75);
            text-transform: uppercase;
            background: rgba(0, 0, 0, 0.6);
            border: 1px solid rgba(255, 255, 255, 0.5);
            cursor: pointer;
            border-radius: 4px;
            padding: 6px 12px;
            pointer-events: all;
        `,
        pageIndicator: `
            position: absolute;
            top: 28px;
            right: 36px;
            font-family: 'Georgia', 'Times New Roman', serif;
            font-size: 30px;
            letter-spacing: 0.14em;
            color: rgba(255, 255, 255, 0.75);
        `,
        // -- Slideshow-specific styles --
        slideImage: `
            position: absolute;
            top: 0; left: 0;
            width: 100%; height: 100%;
            object-fit: cover;
            opacity: 0;
            transition: opacity ${SLIDE_FADE_MS}ms ease;
            pointer-events: none;
        `,
        slideTextWrap: `
            position: absolute;
            left: 0; right: 0;
            bottom: 0;
            display: flex;
            justify-content: center;
            padding: 0 24px 64px 24px;
            box-sizing: border-box;
            pointer-events: none;
        `,
        slideTextBox: `
            max-width: 760px;
            width: 100%;
            text-align: center;
            background: rgba(0, 0, 0, 0.45);
            border-radius: 10px;
            padding: 18px 28px;
            box-sizing: border-box;
        `,
        slideText: `
            font-family: 'Georgia', 'Times New Roman', serif;
            font-size: clamp(15px, 2.4vw, 20px);
            line-height: 1.7;
            color: rgba(255, 255, 255, 0);
            margin: 0;
            transition: color ${SLIDE_FADE_MS}ms ease;
        `,
        // -- Song / karaoke-specific styles --
        songTextWrap: `
            position: absolute;
            left: 0; right: 0;
            bottom: 0;
            display: flex;
            justify-content: center;
            padding: 0 24px 64px 24px;
            box-sizing: border-box;
            pointer-events: none;
        `,
        songTextBox: `
            max-width: 760px;
            width: 100%;
            text-align: center;
            background: rgba(0, 0, 0, 0.45);
            border-radius: 10px;
            padding: 18px 28px;
            box-sizing: border-box;
            display: flex;
            flex-direction: column;
            justify-content: flex-end;
        `,
        // One row per lyric line within the current section.
        songLineRow: `
            font-family: 'Georgia', 'Times New Roman', serif;
            font-size: clamp(14px, 2vw, 18px);
            line-height: 1.6;
            margin: 0;
            min-height: 1.6em;
            transition: opacity 400ms ease;
        `,
        // Letters not yet reached by playback in the active line.
        songLineUnrevealed: `
            color: rgba(255, 255, 255, 0.18);
        `,
        // Letters already sung in the currently-active line.
        songLineRevealedActive: `
            color: rgba(255, 255, 255, 0.95);
        `,
        // Full lines from earlier in the section, already sung — dimmed but
        // still visible, so the whole section builds up rather than vanishing.
        songLineRevealedPast: `
            color: rgba(255, 255, 255, 0.55);
        `,
    };

    const FADE_IN_DELAY_MS = 5000;  // stagger between lines appearing (text-page beats)
    const HINT_DELAY_MS = 1800;    // how long before "click to continue" appears

    let overlay = null;
    let currentPages = [];
    let currentPage = 0;
    let onComplete = null;
    let hintTimeout = null;

    // -- Slideshow-specific state --
    let currentSlides = [];
    let currentSlide = 0;
    let currentSlideImagePath = INTRO_CINEMATIC_IMAGE_PATH;
    let slideAdvanceTimeout = null;
    let slideImgEls = {}; // index -> <img> element (for crossfade between two layers)

    // -- Song / karaoke-specific state --
    let songAudioEl = null;      // the <audio> element driving the karaoke clock
    let songImages = [];         // [{ image, time }] sorted by time
    let songLines = [];          // [{ section, words: [{word, time}] }] sorted by time
    let songImagePath = '';
    let songImgEls = {};         // dom refs, same shape as slideImgEls
    let songRafId = null;        // requestAnimationFrame handle for the sync loop
    let songCurrentImageIdx = -1;
    let songCurrentLineIdx = -1;
    let songCurrentSectionStartIdx = -1; // index in songLines where the active section begins
    let songLineRowEls = [];     // <p> row elements for each line in the current section

    // buildSlideshow — returns { slides, imagePath } for a slideshow beat,
    // or null if the requested beat/variant isn't a slideshow.
    function buildSlideshow(beatId, options = {}) {
        const beat = STORY_BEATS[beatId];
        if (!beat) {
            console.warn(`[Storyline] Unknown beat: "${beatId}"`);
            return null;
        }

        // Top-level slideshow beats (e.g. intro_cinematic)
        if (beat.slides) {
            return { slides: beat.slides, imagePath: beat.imagePath || INTRO_CINEMATIC_IMAGE_PATH };
        }

        // Character-variant slideshow beats (e.g. character_intro)
        if (beat.characterVariants) {
            const char = (options.character || '').toLowerCase();
            const variant = beat.characterVariants[char];
            if (!variant) {
                console.warn(`[Storyline] No character variant "${char}" for beat "${beatId}"`);
                return null;
            }
            if (variant.slides) {
                return { slides: variant.slides, imagePath: variant.imagePath || INTRO_CINEMATIC_IMAGE_PATH };
            }
        }

        return null;
    }

    // buildSong — returns { audio, images, lines, imagePath } for a song beat,
    // or null if the requested beat/variant isn't a song.
    function buildSong(beatId, options = {}) {
        const beat = STORY_BEATS[beatId];
        if (!beat) {
            console.warn(`[Storyline] Unknown beat: "${beatId}"`);
            return null;
        }

        // Top-level song beats
        if (beat.song) {
            return beat.song;
        }

        // Character-variant song beats (e.g. character_intro using songs)
        if (beat.characterVariants) {
            const char = (options.character || '').toLowerCase();
            const variant = beat.characterVariants[char];
            if (!variant) {
                console.warn(`[Storyline] No character variant "${char}" for beat "${beatId}"`);
                return null;
            }
            if (variant.song) {
                return variant.song;
            }
        }

        return null;
    }


    function buildPages(beatId, options = {}) {
        const beat = STORY_BEATS[beatId];
        if (!beat) {
            console.warn(`[Storyline] Unknown beat: "${beatId}"`);
            return null;
        }

        // Slideshow beats (e.g. intro_cinematic) are handled via buildSlideshow
        if (beat.slides) {
            return beat.slides;
        }

        // Character-variant beats
        if (beat.characterVariants) {
            const char = (options.character || '').toLowerCase();
            const variant = beat.characterVariants[char];
            if (!variant) {
                console.warn(`[Storyline] No character variant "${char}" for beat "${beatId}"`);
                return null;
            }
            // Slideshow-style character variants are handled via buildSlideshow
            if (variant.slides) {
                return variant.slides;
            }
            return variant.pages;
        }

        // Class unlock beat (special structure)
        if (beatId === 'class_unlock') {
            const className = options.className || '';
            const classLine = beat.classLines[className] || beat.defaultClassLine;
            return [
                [...beat.shared, classLine]
            ];
        }

        // Ascendency unlock beat (special structure)
        if (beatId === 'ascendency_unlock') {
            const key = (options.ascendencyClass || '').replace(/\s+/g, '');
            return beat.variants[key] || beat.defaultVariant;
        }

        return beat.pages;
    }

    // isSlideshowBeat — true if this beat (given options) should render as
    // an image slideshow rather than a text-page sequence.
    function isSlideshowBeat(beatId, options = {}) {
        const beat = STORY_BEATS[beatId];
        if (!beat) return false;
        if (beat.slides) return true;
        if (beat.characterVariants) {
            const char = (options.character || '').toLowerCase();
            const variant = beat.characterVariants[char];
            return !!(variant && variant.slides);
        }
        return false;
    }

    // isSongBeat — true if this beat (given options) should render as a
    // karaoke-style song (independent image timeline + word-by-word lyric reveal).
    function isSongBeat(beatId, options = {}) {
        const beat = STORY_BEATS[beatId];
        if (!beat) return false;
        if (beat.song) return true;
        if (beat.characterVariants) {
            const char = (options.character || '').toLowerCase();
            const variant = beat.characterVariants[char];
            return !!(variant && variant.song);
        }
        return false;
    }

    function createOverlay() {
        const el = document.createElement('div');
        el.style.cssText = STYLES.overlay;
        return el;
    }

    // -------------------------------------------------------------------
    // TEXT-PAGE RENDERING (multi-line pages, click/space to advance)
    // -------------------------------------------------------------------

    function renderPage(pages, pageIndex) {
        if (!overlay) return;
        overlay.innerHTML = '';

        const lines = pages[pageIndex];
        const box = document.createElement('div');
        box.style.cssText = STYLES.textBox;

        lines.forEach((text, i) => {
            const p = document.createElement('p');
            const isQuote = text.startsWith('"');
            p.style.cssText = isQuote ? STYLES.quotedLine : STYLES.line;
            p.textContent = text;
            box.appendChild(p);

            // Stagger fade-in
            setTimeout(() => {
                p.style.color = isQuote
                    ? 'rgba(255, 255, 255, 0.82)'
                    : 'rgba(255, 255, 255, 0.95)';
            }, i * FADE_IN_DELAY_MS + 80);
        });

        overlay.appendChild(box);

        // Page indicator (only when multi-page)
        if (pages.length > 1) {
            const indicator = document.createElement('div');
            indicator.style.cssText = STYLES.pageIndicator;
            indicator.textContent = `${pageIndex + 1} / ${pages.length}`;
            overlay.appendChild(indicator);
        }

        // "Click to continue" hint
        const hint = document.createElement('div');
        hint.style.cssText = STYLES.hint;
        const isLast = pageIndex === pages.length - 1;
        hint.textContent = isLast ? 'click to continue' : 'click for next';
        overlay.appendChild(hint);

        if (hintTimeout) clearTimeout(hintTimeout);
        const lastLineFadeIn = lines.length * FADE_IN_DELAY_MS + 80;
        const dynamicHintDelay = Math.max(HINT_DELAY_MS, lastLineFadeIn + 600);
        hintTimeout = setTimeout(() => {
            hint.style.color = 'rgba(255, 255, 255, 0.28)';
        }, dynamicHintDelay);
    }

    function advance() {
        currentPage++;
        if (currentPage < currentPages.length) {
            renderPage(currentPages, currentPage);
        } else {
            close();
        }
    }

    // -------------------------------------------------------------------
    // SLIDESHOW RENDERING (image + overlay text, auto-advances by timer)
    // -------------------------------------------------------------------

    function renderSlideshow(slides) {
        if (!overlay) return;
        overlay.innerHTML = '';
        slideImgEls = {};

        // Two stacked <img> layers so we can crossfade between slides.
        const imgA = document.createElement('img');
        const imgB = document.createElement('img');
        imgA.style.cssText = STYLES.slideImage;
        imgB.style.cssText = STYLES.slideImage;
        overlay.appendChild(imgA);
        overlay.appendChild(imgB);
        slideImgEls.layers = [imgA, imgB];
        slideImgEls.activeLayer = 0;

        // Text overlay box (sits above the images)
        const textWrap = document.createElement('div');
        textWrap.style.cssText = STYLES.slideTextWrap;
        const textBox = document.createElement('div');
        textBox.style.cssText = STYLES.slideTextBox;
        const textP = document.createElement('p');
        textP.style.cssText = STYLES.slideText;
        textBox.appendChild(textP);
        textWrap.appendChild(textBox);
        overlay.appendChild(textWrap);
        slideImgEls.textP = textP;

        // Page indicator
        const indicator = document.createElement('div');
        indicator.style.cssText = STYLES.pageIndicator;
        overlay.appendChild(indicator);
        slideImgEls.indicator = indicator;

        // "Click for next" hint
        const hint = document.createElement('div');
        hint.style.cssText = STYLES.hint;
        hint.textContent = 'click for next';
        overlay.appendChild(hint);
        slideImgEls.hint = hint;

        // Skip button
        const skipBtn = document.createElement('button');
        skipBtn.style.cssText = STYLES.skipBtn;
        skipBtn.textContent = 'skip';
        skipBtn.addEventListener('click', (e) => {
            e.stopPropagation(); // don't also advance the slide
            close();
        });
        overlay.appendChild(skipBtn);
        slideImgEls.skipBtn = skipBtn;

        showSlide(slides, 0);
    }

    function showSlide(slides, index) {
        if (!overlay) return;
        if (slideAdvanceTimeout) {
            clearTimeout(slideAdvanceTimeout);
            slideAdvanceTimeout = null;
        }

        const slide = slides[index];
        const duration = slide.duration || DEFAULT_SLIDE_DURATION_MS;

        // Crossfade images: fade out the active layer, fade in the other one.
        const layers = slideImgEls.layers;
        const activeIdx = slideImgEls.activeLayer;
        const nextIdx = activeIdx === 0 ? 1 : 0;

        const outgoing = layers[activeIdx];
        const incoming = layers[nextIdx];

        incoming.src = currentSlideImagePath + slide.image;
        incoming.style.opacity = '0';
        outgoing.style.opacity = '0';

        // Force the new image in front once loaded (or immediately as fallback)
        requestAnimationFrame(() => {
            incoming.style.opacity = '1';
        });

        slideImgEls.activeLayer = nextIdx;

        // Update text (fade out then in)
        const textP = slideImgEls.textP;
        textP.style.color = 'rgba(255, 255, 255, 0)';
        setTimeout(() => {
            textP.textContent = slide.text || '';
            requestAnimationFrame(() => {
                textP.style.color = 'rgba(255, 255, 255, 0.95)';
            });
        }, SLIDE_FADE_MS);

        // Update page indicator
        slideImgEls.indicator.textContent = `${index + 1} / ${slides.length}`;

        // Hint text + style
        const isLast = index === slides.length - 1;
        slideImgEls.hint.textContent = isLast ? 'click to continue' : 'click for next';
        slideImgEls.hint.style.color = 'rgba(255, 255, 255, 0)';
        if (hintTimeout) clearTimeout(hintTimeout);
        hintTimeout = setTimeout(() => {
            slideImgEls.hint.style.color = 'rgba(255, 255, 255, 0.28)';
        }, HINT_DELAY_MS);

        // Auto-advance after `duration` ms
        slideAdvanceTimeout = setTimeout(() => {
            advanceSlide(slides);
        }, duration);
    }

    function advanceSlide(slides) {
        currentSlide++;
        if (currentSlide < slides.length) {
            showSlide(slides, currentSlide);
        } else {
            close();
        }
    }

    // -------------------------------------------------------------------
    // SONG RENDERING (karaoke-style: independent image timeline +
    // word-by-word lyric reveal, both driven off audio.currentTime)
    // -------------------------------------------------------------------

    // Escapes text so it's safe to drop into innerHTML for the per-letter spans.
    function _escapeHtml(str) {
        const div = document.createElement('div');
        div.textContent = str;
        return div.innerHTML;
    }

    function renderSong(song) {
        if (!overlay) return;
        overlay.innerHTML = '';
        songImgEls = {};

        // Two stacked <img> layers so we can crossfade between images,
        // same approach as the regular slideshow.
        const imgA = document.createElement('img');
        const imgB = document.createElement('img');
        imgA.style.cssText = STYLES.slideImage;
        imgB.style.cssText = STYLES.slideImage;
        overlay.appendChild(imgA);
        overlay.appendChild(imgB);
        songImgEls.layers = [imgA, imgB];
        songImgEls.activeLayer = 0;

        // Text overlay box (sits above the images). Holds one row per line
        // in the current section — rows are built fresh each time the
        // section changes (see _buildSectionRows).
        const textWrap = document.createElement('div');
        textWrap.style.cssText = STYLES.songTextWrap;
        const textBox = document.createElement('div');
        textBox.style.cssText = STYLES.songTextBox;
        textWrap.appendChild(textBox);
        overlay.appendChild(textWrap);
        songImgEls.textBox = textBox;

        // Skip button (no page indicator / click-to-advance hint — song beats
        // are driven by audio playback, not click-through)
        const skipBtn = document.createElement('button');
        skipBtn.style.cssText = STYLES.skipBtn;
        skipBtn.textContent = 'skip';
        skipBtn.addEventListener('click', (e) => {
            e.stopPropagation();
            close();
        });
        overlay.appendChild(skipBtn);
        songImgEls.skipBtn = skipBtn;

        // Show the first image immediately (don't wait for the RAF loop's
        // first tick) so there's no blank flash at time 0.
        if (songImages.length > 0) {
            const firstLayer = songImgEls.layers[0];
            firstLayer.src = songImagePath + songImages[0].image;
            firstLayer.style.opacity = '1';
            songImgEls.activeLayer = 0;
            songCurrentImageIdx = 0;
        }
        songCurrentLineIdx = -1;
        songCurrentSectionStartIdx = -1;
        songLineRowEls = [];
    }

    // Swaps to a new image with a crossfade. Mirrors showSlide's image logic
    // but is driven by elapsed playback time rather than a fixed timer.
    function _songSwapImage(imageFile) {
        const layers = songImgEls.layers;
        const activeIdx = songImgEls.activeLayer;
        const nextIdx = activeIdx === 0 ? 1 : 0;

        const outgoing = layers[activeIdx];
        const incoming = layers[nextIdx];

        incoming.src = songImagePath + imageFile;
        incoming.style.opacity = '0';

        requestAnimationFrame(() => {
            incoming.style.opacity = '1';
            outgoing.style.opacity = '0';
        });

        songImgEls.activeLayer = nextIdx;
    }

    // Builds the letter-revealable inner markup for one lyric line (a row's
    // innerHTML). Each word is wrapped in a span holding its own letters,
    // each letter its own span, so we can toggle "revealed" vs "unrevealed"
    // per letter without re-building the DOM every frame.
    function _buildLineMarkup(line) {
        return line.words.map((w, wi) => {
            const letters = w.word.split('').map(ch =>
                `<span class="ka-letter" data-revealed="0">${_escapeHtml(ch)}</span>`
            ).join('');
            const space = wi < line.words.length - 1 ? ' ' : '';
            return `<span class="ka-word">${letters}</span>${space}`;
        }).join('');
    }

    // Finds the contiguous run of songLines that share the same `section`
    // label as songLines[lineIdx], and returns { startIdx, endIdx } (inclusive).
    function _sectionRangeFor(lineIdx) {
        const section = songLines[lineIdx].section;
        let startIdx = lineIdx;
        while (startIdx > 0 && songLines[startIdx - 1].section === section) startIdx--;
        let endIdx = lineIdx;
        while (endIdx < songLines.length - 1 && songLines[endIdx + 1].section === section) endIdx++;
        return { startIdx, endIdx };
    }

    // Rebuilds the text block's row elements for a new section: one empty
    // <p> per line in that section, reserved up to MAX_SONG_SECTION_LINES so
    // the block's height stays constant and doesn't jump between sections.
    function _buildSectionRows(sectionStartIdx, sectionEndIdx) {
        const textBox = songImgEls.textBox;
        textBox.innerHTML = '';
        songLineRowEls = [];

        const lineCount = sectionEndIdx - sectionStartIdx + 1;
        const rowSlots = Math.max(lineCount, MAX_SONG_SECTION_LINES);

        // Empty spacer rows first (so real lines sit at the bottom of the
        // fixed-height block and fill upward, like a karaoke prompter).
        for (let i = 0; i < rowSlots - lineCount; i++) {
            const spacer = document.createElement('p');
            spacer.style.cssText = STYLES.songLineRow;
            textBox.appendChild(spacer);
        }

        for (let i = sectionStartIdx; i <= sectionEndIdx; i++) {
            const row = document.createElement('p');
            row.style.cssText = STYLES.songLineRow;
            row.style.opacity = '0';
            textBox.appendChild(row);
            songLineRowEls.push(row);
        }
    }

    // Given a line's row element and the current playback time, reveals
    // letters up through the word that should be fully sung by now.
    // Interpolates within the current word so it types out smoothly.
    function _updateLineReveal(rowEl, line, nowMs, lineStartMs) {
        const words = line.words;
        const letterSpans = rowEl.querySelectorAll('.ka-letter');
        let letterCursor = 0;

        for (let wi = 0; wi < words.length; wi++) {
            const word = words[wi];
            const wordLen = word.word.length;
            const wordStart = wi === 0 ? lineStartMs : words[wi - 1].time;
            const wordEnd = word.time;

            let revealCount;
            if (nowMs >= wordEnd) {
                revealCount = wordLen; // fully sung
            } else if (nowMs <= wordStart) {
                revealCount = 0; // not started yet
            } else {
                const progress = (nowMs - wordStart) / Math.max(1, wordEnd - wordStart);
                revealCount = Math.floor(progress * wordLen);
            }

            for (let li = 0; li < wordLen; li++) {
                const span = letterSpans[letterCursor + li];
                if (!span) continue;
                const shouldReveal = li < revealCount;
                if (shouldReveal && span.dataset.revealed !== '1') {
                    span.dataset.revealed = '1';
                    span.style.color = 'rgba(255, 255, 255, 0.95)';
                } else if (!shouldReveal && span.dataset.revealed !== '0') {
                    span.dataset.revealed = '0';
                    span.style.color = 'rgba(255, 255, 255, 0.18)';
                }
            }
            letterCursor += wordLen;
        }
    }

    // Dims a row's letters to the "already sung, but earlier in this
    // section" style — fully visible, just lower emphasis than the active line.
    function _dimRowToPast(rowEl) {
        rowEl.querySelectorAll('.ka-letter').forEach(span => {
            span.style.color = 'rgba(255, 255, 255, 0.55)';
        });
    }

    // The main sync loop — ticks every animation frame while the song plays.
    // Reads the audio element's real playback time and updates whichever
    // image / lyric line should be showing at that moment.
    function _songSyncTick() {
        if (!overlay || !songAudioEl) return;

        const nowMs = songAudioEl.currentTime * 1000;

        // -- Image timeline: advance to the latest image whose time has passed --
        let targetImageIdx = songCurrentImageIdx;
        for (let i = 0; i < songImages.length; i++) {
            if (songImages[i].time <= nowMs) targetImageIdx = i;
            else break;
        }
        if (targetImageIdx !== songCurrentImageIdx && targetImageIdx >= 0) {
            songCurrentImageIdx = targetImageIdx;
            _songSwapImage(songImages[targetImageIdx].image);
        }

        // -- Lyric timeline: find the active line (the last line whose first
        //    word has started, defaulting to line 0 even before its first
        //    word's reveal-time so something is always on screen) --
        let targetLineIdx = 0;
        for (let i = 0; i < songLines.length; i++) {
            const firstWordTime = songLines[i].words[0] ? songLines[i].words[0].time : 0;
            if (firstWordTime <= nowMs) {
                targetLineIdx = i;
            } else {
                break;
            }
        }

        if (targetLineIdx !== songCurrentLineIdx && songLines.length > 0) {
            const prevLineIdx = songCurrentLineIdx;
            songCurrentLineIdx = targetLineIdx;

            const { startIdx, endIdx } = _sectionRangeFor(targetLineIdx);

            if (startIdx !== songCurrentSectionStartIdx) {
                // New section — clear the block and reserve fresh rows.
                songCurrentSectionStartIdx = startIdx;
                _buildSectionRows(startIdx, endIdx);
            } else if (prevLineIdx >= 0 && prevLineIdx >= startIdx) {
                // Same section, just moved to the next line in it — dim the
                // row we just finished singing, then move on.
                const prevRow = songLineRowEls[prevLineIdx - startIdx];
                if (prevRow) _dimRowToPast(prevRow);
            }

            // Reveal (fade in) and populate the row for the new active line.
            const row = songLineRowEls[targetLineIdx - startIdx];
            if (row) {
                row.innerHTML = _buildLineMarkup(songLines[targetLineIdx]);
                requestAnimationFrame(() => { row.style.opacity = '1'; });
            }
        }

        // Progressively reveal letters within the active line
        if (songCurrentLineIdx >= 0 && songCurrentSectionStartIdx >= 0) {
            const line = songLines[songCurrentLineIdx];
            const prevLine = songLines[songCurrentLineIdx - 1];
            const lineStartMs = prevLine ? prevLine.words.slice(-1)[0].time : 0;
            const row = songLineRowEls[songCurrentLineIdx - songCurrentSectionStartIdx];
            if (row) _updateLineReveal(row, line, nowMs, lineStartMs);
        }

        // Stop the loop once the track ends (or once it's paused/closed elsewhere)
        if (songAudioEl.ended) {
            close();
            return;
        }

        songRafId = requestAnimationFrame(_songSyncTick);
    }

    // Starts a song beat: plays the audio and kicks off the sync loop.
    // Falls back to a timer-driven close if autoplay is blocked, so the
    // beat doesn't hang forever waiting on a play() promise that never resolves.
    function startSong(song) {
        songImages = (song.images || []).slice().sort((a, b) => a.time - b.time);
        songLines = (song.lines || []).slice().sort((a, b) => {
            const at = a.words[0] ? a.words[0].time : 0;
            const bt = b.words[0] ? b.words[0].time : 0;
            return at - bt;
        });
        songImagePath = song.imagePath || INTRO_CINEMATIC_IMAGE_PATH;
        songCurrentImageIdx = -1;
        songCurrentLineIdx = -1;
        songCurrentSectionStartIdx = -1;
        songLineRowEls = [];

        renderSong(song);

        songAudioEl = new Audio(song.audio);
        songAudioEl.volume = 1.0;

        songAudioEl.addEventListener('ended', close);

        songAudioEl.play().then(() => {
            songRafId = requestAnimationFrame(_songSyncTick);
        }).catch(() => {
            // Autoplay blocked — resume on first user interaction, same
            // pattern as Audio_Manager's BGM autoplay-resume fallback.
            const resume = () => {
                songAudioEl.play().then(() => {
                    songRafId = requestAnimationFrame(_songSyncTick);
                }).catch(() => { });
                document.removeEventListener('click', resume);
                document.removeEventListener('keydown', resume);
            };
            document.addEventListener('click', resume, { once: true });
            document.addEventListener('keydown', resume, { once: true });
        });
    }

    function stopSong() {
        if (songRafId) {
            cancelAnimationFrame(songRafId);
            songRafId = null;
        }
        if (songAudioEl) {
            songAudioEl.removeEventListener('ended', close);
            songAudioEl.pause();
            songAudioEl.currentTime = 0;
            songAudioEl = null;
        }
    }

    function close() {
        if (!overlay) return;
        if (slideAdvanceTimeout) {
            clearTimeout(slideAdvanceTimeout);
            slideAdvanceTimeout = null;
        }
        stopSong();
        overlay.style.transition = 'opacity 0.7s ease';
        overlay.style.opacity = '0';
        setTimeout(() => {
            if (overlay && overlay.parentNode) overlay.parentNode.removeChild(overlay);
            overlay = null;
            if (typeof onComplete === 'function') onComplete();
        }, 720);
    }

    // -------------------------------------------------------------------
    // PUBLIC
    // -------------------------------------------------------------------

    function show(beatId, options = {}) {
        const isSong = isSongBeat(beatId, options);
        const isSlideshow = !isSong && isSlideshowBeat(beatId, options);

        let pages = null;
        let slideshow = null;
        let song = null;

        if (isSong) {
            song = buildSong(beatId, options);
            if (!song || !song.audio) return;
        } else if (isSlideshow) {
            slideshow = buildSlideshow(beatId, options);
            if (!slideshow || !slideshow.slides || slideshow.slides.length === 0) return;
        } else {
            pages = buildPages(beatId, options);
            if (!pages || pages.length === 0) return;
        }

        // Skip if already seen (unless forced)
        if (!options.force && hasSeen(beatId, options)) return;
        markSeen(beatId, options);

        onComplete = options.onComplete || null;

        overlay = createOverlay();
        document.body.appendChild(overlay);

        if (isSong) {
            startSong(song);
            // Clicking/space does NOT skip a song beat — playback drives it.
            // Only the explicit skip button (rendered in renderSong) closes it early.
        } else if (isSlideshow) {
            currentSlides = slideshow.slides;
            currentSlideImagePath = slideshow.imagePath || INTRO_CINEMATIC_IMAGE_PATH;
            currentSlide = 0;
            renderSlideshow(currentSlides);

            // Click anywhere to advance / close
            overlay.addEventListener('click', () => advanceSlide(currentSlides));

            function onKeySlide(e) {
                if (e.code === 'Space' || e.code === 'Enter') {
                    e.preventDefault();
                    advanceSlide(currentSlides);
                }
            }
            document.addEventListener('keydown', onKeySlide);
        } else {
            currentPages = pages;
            currentPage = 0;
            renderPage(currentPages, currentPage);

            // Click anywhere to advance / close
            overlay.addEventListener('click', advance);

            // Keyboard: Space or Enter also advance
            function onKey(e) {
                if (e.code === 'Space' || e.code === 'Enter') {
                    e.preventDefault();
                    advance();
                }
            }
            document.addEventListener('keydown', onKey);
            // Remove listener when overlay closes
            // (listener is cleaned up when overlay is removed from DOM — acceptable for this use case)
        }
    }

    return { show };

})();


// ---------------------------------------------------------------------------
// SEEN-STATE — uses localStorage so beats only show once per save
// ---------------------------------------------------------------------------

function _seenKey(beatId, options = {}) {
    // For character beats, include character id in key
    const suffix = options.character
        ? `_${options.character}`
        : options.className
            ? `_${options.className}`
            : options.ascendencyClass
                ? `_${options.ascendencyClass}`
                : '';
    return `storyline_seen_${beatId}${suffix}`;
}

function hasSeen(beatId, options = {}) {
    try {
        return localStorage.getItem(_seenKey(beatId, options)) === '1';
    } catch (e) {
        return false;
    }
}

function markSeen(beatId, options = {}) {
    try {
        localStorage.setItem(_seenKey(beatId, options), '1');
    } catch (e) { /* storage unavailable */ }
}

// Allow resetting a specific beat (useful for testing)
function resetBeat(beatId, options = {}) {
    try {
        localStorage.removeItem(_seenKey(beatId, options));
    } catch (e) { /* noop */ }
}

// Reset all story beats at once (e.g. new game)
function resetAllBeats() {
    try {
        Object.keys(localStorage)
            .filter(k => k.startsWith('storyline_seen_'))
            .forEach(k => localStorage.removeItem(k));
    } catch (e) { /* noop */ }
}


// ---------------------------------------------------------------------------
// PUBLIC API
// ---------------------------------------------------------------------------

/**
 * showBeat(beatId, options)
 *
 * beatId      — key from STORY_BEATS (e.g. 'intro_cinematic', 'region_5')
 * options     — {
 *   character:       'stox' | 'trix' | 'syla'      (for character_intro)
 *   className:       'Mathmagician' | ...           (for class_unlock)
 *   ascendencyClass: 'Outlier' | ...                 (for ascendency_unlock)
 *   force:           true                           (show even if already seen)
 *   onComplete:      function                       (called after the beat closes)
 * }
 *
 * Beats are shown only once per save by default (localStorage flag).
 * Pass { force: true } to override — handy for replaying in a codex / gallery.
 */
function showBeat(beatId, options = {}) {
    StorylineRenderer.show(beatId, options);
}