// =============================================================================
// storyline-intro.js — The Cartographers of Chance
// ---------------------------------------------------------------------------
// Data for the main opening cinematic / intro song (Part 1).
// Depends on: storyline-engine.js (_wordsFromLine, MAX_SONG_SECTION_LINES,
// DEFAULT_SLIDE_DURATION_MS, SLIDE_FADE_MS) — must load AFTER that file.
// =============================================================================

// ---------------------------------------------------------------------------
// INTRO CINEMATIC — IMAGE SLIDESHOW (Part 1: Opening Cinematic)
// ---------------------------------------------------------------------------
//
// Each slide shows one image from images/Intro/Stoxels_Intro/ (1.jpeg ... 24.jpeg)
// for `duration` milliseconds, with `text` overlaid on top.
// After the duration elapses, it auto-advances to the next slide.
// Clicking / pressing space also advances early.
// After the last slide, the cinematic closes and onComplete fires.
//
// Adjust `duration` per-slide as needed, or change DEFAULT_SLIDE_DURATION_MS
// below for a global default.
// ---------------------------------------------------------------------------

const INTRO_CINEMATIC_SLIDES = [
    { image: "1.jpeg", text: "Reality is not made of matter.", duration: 8000 },
    { image: "2.jpeg", text: "It is made of data.", duration: 8000 },
    { image: "3.jpeg", text: "Probabilities. Statistical patterns. All of it woven into a living fabric - The Sample Space.", duration: 12000 },
    { image: "4.jpeg", text: "Everything that exists - mountains, oceans, creatures, time itself - is output. Generated by an ancient device.", duration: 12000 },
    { image: "5.jpeg", text: "Built long ago, by a civilisation of scholars who called themselves the First Cartographers.", duration: 11000 },
    { image: "6.jpeg", text: "Their greatest achievement - they called it the Apex of Stochastics.", duration: 9000 },
    { image: "7.jpeg", text: "Designed to keep the Sample Space coherent. Forever.", duration: 9000 },
    { image: "8.jpeg", text: "Ensuring randomness stayed honest - that the universe kept generating a coherent reality.", duration: 11000 },
    { image: "9.jpeg", text: "But then came the Variance Collapse.", duration: 8000 },
    { image: "10.jpeg", text: "The Apex began to corrupt.", duration: 8000 },
    { image: "11.jpeg", text: "The Sample Space began to fracture.", duration: 8000 },
    { image: "12.jpeg", text: "Split into thirteen distorted regions, each warped by its own statistical anomaly.", duration: 11000 },
    { image: "13.jpeg", text: "Most of the First Cartographers were lost in the chaos that followed.", duration: 10000 },
    { image: "14.jpeg", text: "A handful survived, and retreated to a small outpost at the edge of the world.", duration: 10000 },
    { image: "15.jpeg", text: "The survivors founded a Guild, to keep what they knew from being lost a second time.", duration: 11000 },
    { image: "16.jpeg", text: "In three hundred years, nobody has reached the Apex again.", duration: 10000 },
    { image: "17.jpeg", text: "The thirteen regions have remained in flux ever since.", duration: 9000 },
    { image: "18.jpeg", text: "Locked in place - by manifestations of pure void called Stoxels.", duration: 9000 },
    { image: "19.jpeg", text: "Collapsed knots of warped probability, binding the corruption to this place and keeping the land from healing.", duration: 10000 },
    { image: "24.jpeg", text: "They cannot be destroyed. Not by force, not by magic - nothing the First Cartographers tried ever worked.", duration: 11000 },
    { image: "20.jpeg", text: "A Stoxel cannot be broken. It can only be solved - the hidden pattern found, and filled, by someone who reads the mathematical language it was written in.", duration: 13000 },
    { image: "21.jpeg", text: "The Cartographers' Guild has been training young recruits for this task." },
    { image: "22.jpeg", text: "They call themselves the Cartographers of Chance." },
    { image: "23.jpeg", text: "And you... are one of them." },
];



// Folder where the intro images live (relative to your index.html)
const INTRO_CINEMATIC_IMAGE_PATH = "images/Intro/Stoxels_Intro/";



// ---------------------------------------------------------------------------
// SONG BEATS — karaoke-style intro (Part 1.5: vocal intro song)
// ---------------------------------------------------------------------------
//
// A "song" beat decouples images from text completely:
//   - `images` is its own timeline: [{ image, time }], time = ms from song start.
//     A new image is shown as soon as playback crosses that time.
//   - `lines` is the lyric timeline: each line is { section, words: [{ word, time }] }.
//     `time` on a word = the ms (from song start) at which that word should be
//     FULLY revealed (i.e. finished being "sung"). Letters within the word are
//     revealed by interpolating between the previous word's time and this one.
//     `section` groups lines (Verse 1, Chorus, etc.) — lines in the same
//     section accumulate on screen together; a new section clears the block.
//   - `audio` is the path to the vocal track. Playback of this file IS the
//     master clock — both images and lyrics sync to audioEl.currentTime.
//

// INTRO_SONG — full intro song, timed from Stoxels_Intro_Song.srt.
// Each line's start/end comes directly from the SRT (real vocal timing).
// Word-level reveal within each line is still interpolated evenly across
// that line's SRT window via _wordsFromLine — true word-by-word timestamps
// would need finer-grained data than SRT provides (SRT is line-level only),
// but this means every line change is locked exactly to the vocals, and the
// typewriter effect within a line plays out at a steady pace across the
// real duration that line is actually sung for.
//
// Regenerate this block any time the SRT changes by re-running the same
// parse script used to build it (parses the .srt, emits one
// _wordsFromLine(...) call per cue with that cue's real start/end ms).
const INTRO_SONG = {
    audio: "audio/Intro/Stoxels_Intro_Song.mp3",
    imagePath: INTRO_CINEMATIC_IMAGE_PATH,

    // Image timeline — one change roughly every 2 lyric lines, snapped to
    // that line's real start time, cycling through images 1-24. Adjust
    // freely — this list is independent of the lyric timing below.
    images: [
        { image: "0.jpeg", time: 0},
        { image: "1.jpeg", time: 5000 },
        { image: "2.jpeg", time: 22000 },
        { image: "3.jpeg", time: 32000 },
        { image: "4.jpeg", time: 38000 },
        { image: "5.jpeg", time: 54500 },
        { image: "6.jpeg", time: 60000 },
        { image: "7.jpeg", time: 67000 },
        { image: "8.jpeg", time: 77000 },
        { image: "9.jpeg", time: 86500 },
        { image: "10.jpeg", time: 93000 },
        { image: "11.jpeg", time: 98500 },
        { image: "12.jpeg", time: 105500 },
        { image: "13.jpeg", time: 110500 },
        { image: "14.jpeg", time: 115500 },
        { image: "15.jpeg", time: 120500 },
        { image: "16.jpeg", time: 132500 },
        { image: "17.jpeg", time: 138000 },
        { image: "18.jpeg", time: 148000 },
        { image: "19.jpeg", time: 154000 },
        { image: "20.jpeg", time: 161000 },
        { image: "21.jpeg", time: 164000 },
        { image: "22.jpeg", time: 168500 },
        { image: "23.jpeg", time: 174000 },
        { image: "24.jpeg", time: 177000 },
        { image: "25.jpeg", time: 182500 },
        { image: "26.jpeg", time: 187500 },
        { image: "27.jpeg", time: 194000 },
        { image: "28.jpeg", time: 198000 },
        { image: "29.jpeg", time: 208500 },
        { image: "30.jpeg", time: 213500 },
        { image: "31.jpeg", time: 220500 },
        { image: "32.jpeg", time: 229000 },
        { image: "33.jpeg", time: 238000 },
        { image: "34.jpeg", time: 247000 },
        { image: "35.jpeg", time: 256000 },
        { image: "36.jpeg", time: 265001 },
        { image: "37.jpeg", time: 276501 },


    ],

    // Lyric timeline — all 66 lines from the SRT, in order, using each
    // line's real start/end time as the word-reveal window. Each line also
    // carries a `section` label (Verse 1, Chorus, Bridge, etc.) — lines in
    // the same section accumulate in the display block; a new section
    // clears the block and starts fresh. See SONG_SECTION_ORDER below if
    // you need the max lines-per-section for layout sizing.
    lines: [
        { section: 'Verse 1', words: _wordsFromLine('They say the world is matter', 15500, 18999) },
        { section: 'Verse 1', words: _wordsFromLine('Stone and sea and skin', 19000, 22000) },
        { section: 'Verse 1', words: _wordsFromLine('But underneath the surface', 22001, 24500) },
        { section: 'Verse 1', words: _wordsFromLine('It\'s numbers running thin', 24501, 28500) },
        { section: 'Verse 1', words: _wordsFromLine('Just probabilities dancing', 28501, 31999) },
        { section: 'Verse 1', words: _wordsFromLine('In a fabric none can see', 32000, 34999) },
        { section: 'Verse 1', words: _wordsFromLine('This is the Sample Space we\'re born from', 35001, 37999) },
        { section: 'Verse 1', words: _wordsFromLine('This is how we came to be', 38000, 42000) },

        { section: 'Verse 2', words: _wordsFromLine('Every mountain, every ocean', 54500, 58000) },
        { section: 'Verse 2', words: _wordsFromLine('Every creature, every hour', 58001, 60000) },          
        { section: 'Verse 2', words: _wordsFromLine('Was written by an ancient engine', 60001, 64000) },    
        { section: 'Verse 2', words: _wordsFromLine('Built with old and patient power', 64001, 67000) },
        { section: 'Verse 2', words: _wordsFromLine('Scholars called the First Cartographers', 67001, 71000) },
        { section: 'Verse 2', words: _wordsFromLine('Raised it from the stone', 71001, 73500) },
        { section: 'Verse 2', words: _wordsFromLine('The Apex of all Stochastics', 73501, 77000) },
        { section: 'Verse 2', words: _wordsFromLine('Standing there alone', 77001, 80000) },


        { section: 'Pre-Chorus', words: _wordsFromLine('Built to keep the chaos honest', 80001, 83499) },
        { section: 'Pre-Chorus', words: _wordsFromLine('Built to hold the pattern true', 83500, 86500) },
        { section: 'Pre-Chorus', words: _wordsFromLine('Forever, they believed it', 86501, 89500) },
        { section: 'Pre-Chorus', words: _wordsFromLine('Forever, they thought they knew', 89001, 93000) },

        { section: 'Chorus', words: _wordsFromLine('But nothing built can last forever', 93001, 96000) }, 
        { section: 'Chorus', words: _wordsFromLine('Nothing measured stays the same', 96001, 98499) },      
        { section: 'Chorus', words: _wordsFromLine('Something broke the Variance open', 98500, 101999) }, 
        { section: 'Chorus', words: _wordsFromLine('Something tore the world\'s frame', 102000, 105500) },
        { section: 'Chorus', words: _wordsFromLine('Thirteen pieces, scattered, warping', 105501, 109000) },
        { section: 'Chorus', words: _wordsFromLine('Thirteen wounds that never close', 109001, 111500) },
        { section: 'Chorus', words: _wordsFromLine('This is the Collapse we\'re living after', 111501, 114000) },
        { section: 'Chorus', words: _wordsFromLine('This is the world the Cartographers chose', 114001, 125000) },


        { section: 'Verse 3', words: _wordsFromLine('Most of them were lost that day', 132500, 134500) }, 
        { section: 'Verse 3', words: _wordsFromLine('Swallowed by the breaking tide', 134501, 138500) },    
        { section: 'Verse 3', words: _wordsFromLine('A handful crawled to the edges of the world', 138001, 142000) }, 
        { section: 'Verse 3', words: _wordsFromLine('And built a Guild to hide', 142001, 145000) },
        { section: 'Verse 3', words: _wordsFromLine('Three hundred years have passed us', 145001, 148000) },
        { section: 'Verse 3', words: _wordsFromLine('And no one\'s touched the Apex since', 148001, 151000) }, 
        { section: 'Verse 3', words: _wordsFromLine('Thirteen regions caught in flux', 151001, 154000) },
        { section: 'Verse 3', words: _wordsFromLine('Held by something we call Stoxels', 154001, 158000) }, 


        { section: 'Pre-Chorus', words: _wordsFromLine('Pure void, locked in pattern', 158001, 161000) },
        { section: 'Pre-Chorus', words: _wordsFromLine('Nothing breaks them, nothing can', 161001, 164000) },
        { section: 'Pre-Chorus', words: _wordsFromLine('No blade, no spell, no fire', 164001, 166500) },
        { section: 'Pre-Chorus', words: _wordsFromLine('Only the mind of one who understands', 166501, 170999) },

        { section: 'Chorus', words: _wordsFromLine('But nothing built can last forever', 171000, 174000) },
        { section: 'Chorus', words: _wordsFromLine('Nothing measured stays the same', 174001, 177000) },
        { section: 'Chorus', words: _wordsFromLine('A Stoxel can\'t be broken open', 177001, 180499) },
        { section: 'Chorus', words: _wordsFromLine('Only solved, only named', 180500, 184000) },
        { section: 'Chorus', words: _wordsFromLine('Read the language hidden in it', 184001, 187500) },
        { section: 'Chorus', words: _wordsFromLine('Find the number, find the door', 187501, 190500) },
        { section: 'Chorus', words: _wordsFromLine('This is the Collapse we\'re living after', 190501, 194000) },
        { section: 'Chorus', words: _wordsFromLine('This is what we\'re fighting for', 194001, 198000) },   

        { section: 'Bridge', words: _wordsFromLine('The Guild has trained its children', 198001, 200500) }, 
        { section: 'Bridge', words: _wordsFromLine('For longer than they\'ve known', 200501, 208500) },
        { section: 'Bridge', words: _wordsFromLine('Calling themselves the Cartographers of Chance', 208501, 213000) }, 
        { section: 'Bridge', words: _wordsFromLine('Walking out alone', 213001, 220500) }, 
        { section: 'Bridge', words: _wordsFromLine('And maybe it was always you', 220501, 224000) },
        { section: 'Bridge', words: _wordsFromLine('Maybe it was always meant to be', 224001, 228500) },
        { section: 'Bridge', words: _wordsFromLine('The one who reads the pattern', 228501, 232000) },
        { section: 'Bridge', words: _wordsFromLine('The one who sets it free', 232001, 235500) },   //

        { section: 'Final Chorus', words: _wordsFromLine('Because nothing built can last forever', 235501, 241500) },
        { section: 'Final Chorus', words: _wordsFromLine('But nothing broken has to stay', 241501, 249000) },
        { section: 'Final Chorus', words: _wordsFromLine('Every Stoxel holds a number', 249001, 252500) },
        { section: 'Final Chorus', words: _wordsFromLine('Waiting for the one who\'ll stay', 252501, 255500) },
        { section: 'Final Chorus', words: _wordsFromLine('Thirteen regions, calling, calling', 255501, 258500) },
        { section: 'Final Chorus', words: _wordsFromLine('You\'re the answer they\'ve been waiting for', 258501, 262000) },
        { section: 'Final Chorus', words: _wordsFromLine('This is the Collapse we\'re living after', 262001, 265000) },
        { section: 'Final Chorus', words: _wordsFromLine('And you... you\'re walking through that door', 265001, 270000) },

        { section: 'Outro', words: _wordsFromLine('And you...', 270001, 275500) },
        { section: 'Outro', words: _wordsFromLine('Are one of them', 275501, 286000) },
    ],
};